{{- if .Values.secrets.huggingface.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeai.huggingfaceSecretName" . }}
  labels:
    {{- include "kubeai.labels" . | nindent 4 }}
data:
  token: {{ .Values.secrets.huggingface.token | b64enc }}
{{- end }}